# Set theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Marco Peterson
description: Data Scientist — forecasting, segmentation, predictive analytics
author: Marco Peterson

# (optional) Google Analytics
# google_analytics: G-XXXXXXX

# Social
social-network-links:
  email: "mapeterson3@outlook.com"
  linkedin: marco-peterson-5b1b63148
  github: MarcoPeterson

theme: jekyll-theme-minimal
